"""Add planner: plans, checklist items, childcare arrangement

Revision ID: 79d5becb064e
Revises: ec341b226d32
Create Date: 2026-07-18 21:54:11.838443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d5becb064e'
down_revision = 'ec341b226d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return_to_work_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('work_type', sa.String(length=20), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('return_to_work_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_to_work_plans_user_id'), ['user_id'], unique=False)

    op.create_table('checklist_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['return_to_work_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_items_plan_id'), ['plan_id'], unique=False)

    op.create_table('childcare_arrangements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('primary_caregiver', sa.String(length=255), nullable=True),
    sa.Column('backup_plan', sa.Text(), nullable=True),
    sa.Column('commute_notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['return_to_work_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('childcare_arrangements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_childcare_arrangements_plan_id'), ['plan_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('childcare_arrangements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_childcare_arrangements_plan_id'))

    op.drop_table('childcare_arrangements')
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_items_plan_id'))

    op.drop_table('checklist_items')
    with op.batch_alter_table('return_to_work_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_return_to_work_plans_user_id'))

    op.drop_table('return_to_work_plans')
    # ### end Alembic commands ###
