"""Add baby_birth_date to users

Revision ID: 1bf631121e96
Revises: bc7fac901e71
Create Date: 2026-07-19 14:06:31.959837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf631121e96'
down_revision = 'bc7fac901e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baby_birth_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('baby_birth_date')

    # ### end Alembic commands ###
