"""Add wellbeing check-ins

Revision ID: caa922d37c24
Revises: 79d5becb064e
Create Date: 2026-07-18 22:50:02.359545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa922d37c24'
down_revision = '79d5becb064e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_ins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mood_score', sa.Integer(), nullable=False),
    sa.Column('stress_score', sa.Integer(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_check_ins_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_check_ins_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_check_ins_user_id'))
        batch_op.drop_index(batch_op.f('ix_check_ins_created_at'))

    op.drop_table('check_ins')
    # ### end Alembic commands ###
