"""Add billing: subscriptions and employer organizations

Revision ID: deff0db9d371
Revises: 1bf631121e96
Create Date: 2026-07-19 23:26:03.555922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deff0db9d371'
down_revision = '1bf631121e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer_organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('seat_limit', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employer_organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employer_organizations_admin_user_id'), ['admin_user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_employer_organizations_invite_code'), ['invite_code'], unique=True)

    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=True)

    op.create_table('employer_enrollments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('mother_user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mother_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['employer_organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'mother_user_id', name='uq_org_mother')
    )
    with op.batch_alter_table('employer_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employer_enrollments_mother_user_id'), ['mother_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employer_enrollments_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employer_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employer_enrollments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_employer_enrollments_mother_user_id'))

    op.drop_table('employer_enrollments')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('employer_organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employer_organizations_invite_code'))
        batch_op.drop_index(batch_op.f('ix_employer_organizations_admin_user_id'))

    op.drop_table('employer_organizations')
    # ### end Alembic commands ###
